# Generated by Django 5.0.1 on 2024-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busy_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('Exercise1', models.TextField(max_length=100)),
                ('Exercise2', models.TextField(max_length=100)),
                ('Exercise3', models.TextField(max_length=100)),
                ('Exercise4', models.TextField(max_length=100)),
                ('Exercise5', models.TextField(max_length=100)),
                ('Exercise6', models.TextField(max_length=100)),
                ('Exercise7', models.TextField(max_length=100)),
                ('Exercise8', models.TextField(max_length=100)),
                ('Exercise9', models.TextField(max_length=100)),
                ('Exercise10', models.TextField(max_length=100)),
                ('Exercise11', models.TextField(max_length=100)),
                ('Exercis12', models.TextField(max_length=100)),
                ('Exercise13', models.TextField(max_length=100)),
                ('Exercise14', models.TextField(max_length=100)),
                ('Exercise15', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diet_Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('goals', models.CharField(max_length=50)),
                ('bodytype', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('Tip1', models.TextField(max_length=100)),
                ('Tip2', models.TextField(max_length=100)),
                ('Tip3', models.TextField(max_length=100)),
                ('Tip4', models.TextField(max_length=100)),
                ('Tip5', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Free_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('Exercise1', models.TextField(max_length=100)),
                ('Exercise2', models.TextField(max_length=100)),
                ('Exercise3', models.TextField(max_length=100)),
                ('Exercise4', models.TextField(max_length=100)),
                ('Exercise5', models.TextField(max_length=100)),
                ('Exercise6', models.TextField(max_length=100)),
                ('Exercise7', models.TextField(max_length=100)),
                ('Exercise8', models.TextField(max_length=100)),
                ('Exercise9', models.TextField(max_length=100)),
                ('Exercise10', models.TextField(max_length=100)),
                ('Exercise11', models.TextField(max_length=100)),
                ('Exercis12', models.TextField(max_length=100)),
                ('Exercise13', models.TextField(max_length=100)),
                ('Exercise14', models.TextField(max_length=100)),
                ('Exercise15', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('Exercise1', models.TextField(max_length=100)),
                ('Exercise2', models.TextField(max_length=100)),
                ('Exercise3', models.TextField(max_length=100)),
                ('Exercise4', models.TextField(max_length=100)),
                ('Exercise5', models.TextField(max_length=100)),
                ('Exercise6', models.TextField(max_length=100)),
                ('Exercise7', models.TextField(max_length=100)),
                ('Exercise8', models.TextField(max_length=100)),
                ('Exercise9', models.TextField(max_length=100)),
                ('Exercise10', models.TextField(max_length=100)),
                ('Exercise11', models.TextField(max_length=100)),
                ('Exercis12', models.TextField(max_length=100)),
                ('Exercise13', models.TextField(max_length=100)),
                ('Exercise14', models.TextField(max_length=100)),
                ('Exercise15', models.TextField(max_length=100)),
            ],
        ),
    ]
