# Generated by Django 5.0.1 on 2024-02-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizLogic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busy_workout',
            old_name='Exercis12',
            new_name='Exercise12',
        ),
        migrations.RenameField(
            model_name='free_workout',
            old_name='Exercis12',
            new_name='Exercise12',
        ),
        migrations.RenameField(
            model_name='home_workout',
            old_name='Exercis12',
            new_name='Exercise12',
        ),
        migrations.AddField(
            model_name='busy_workout',
            name='Description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='free_workout',
            name='Description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='home_workout',
            name='Description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
