# Generated by Django 5.0.1 on 2024-02-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizLogic', '0002_rename_exercis12_busy_workout_exercise12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet_tips',
            name='time',
        ),
    ]
