# Generated by Django 5.0.1 on 2024-02-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizLogic', '0003_remove_diet_tips_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_tips',
            name='Tip1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diet_tips',
            name='Tip2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diet_tips',
            name='Tip3',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diet_tips',
            name='Tip4',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diet_tips',
            name='Tip5',
            field=models.TextField(max_length=200),
        ),
    ]
